### ISSUE TITLE
Is there a way to have the latest editor?

### ISSUE THREAD

**Issue by EmbraceLife** [shiffman/Video-Lesson-Materials#12]
Hi Dan,
As bugs are fixed along the way, but it won't be updated quickly for the version we downloaded from processing.org. I wonder whether I can also have the latest editor you are using at the moment? Do I need to fork the p5.js editor repo to do it?

**Comment by shiffman** [comment]
Yeah, I'm using a slightly newer version of the editor.  Less important than that though are the p5.js library files themselves.  You can grab the latest from p5js.org or also:

http://cdnjs.com/libraries/p5.js/

You'll have to manually update the files in the "libraries" folder while the editor is not open.

**Comment by EmbraceLife** [comment]
Thanks
