### ISSUE TITLE
7.13.3 and 7.13.4 are not working due to `this.parent()` ?

### ISSUE THREAD

**Issue by EmbraceLife** [shiffman/Video-Lesson-Materials#13]
Hi Dan,
both programs have the same error and I don't know where is the problem:
`12684: Uncaught TypeError: Cannot read property 'appendChild' of undefined`

I think both programs may have something to do with:
```javascript
  var paragraph = this.parent();
  img.parent(paragraph);
```
Also I don't have the apple image you used. 

Thanks,
kenny

**Comment by shiffman** [comment]
Ah, `parent()` returning the existing parent is a new feature of p5.dom.  So make sure you update the p5.js and p5.dom.js library files to the most recent (you'll have to do this manually unfortunately).  

I pulled the apple image from a [google image search](https://www.google.com/search?q=apple&es_sm=91&source=lnms&tbm=isch&sa=X&ved=0CAgQ_AUoAmoVChMI5p-8l4nfyAIVA3k-Ch1_pAbN&biw=1309&bih=667).  I can't remember which one it is but I think that's not so important!

**Comment by EmbraceLife** [comment]
I see, now it works, thanks. (your video 7.5 showed me how exactly) and I will upload an apple image
