### ISSUE TITLE
In 6.9_p5.js_checking_objects_intersection_1 Lines 12-13 are wrong

### ISSUE THREAD

**Issue by thetimetraveller** [shiffman/Video-Lesson-Materials#19]
Lines 12-13 should be:

  b1 = new Bubble(250, 200);
  b2 = new Bubble(350, 200);

instead of:

  var b1 = new Bubble(250, 200);
  var b2 = new Bubble(350, 200);

otherwise you get the error:
19: Uncaught TypeError: Cannot read property 'update' of undefined

Variables b1 & b2 are already defined in lines 6-7.

P.S. Daniel, thanks SO MUCH for your effort in making these videos. I'm learning a lot!!
Keep it up, you rule, man!
Greetings from Spain.

**Comment by shiffman** [comment]
Thank you for pointing this out!  Fixed!  You are always welcome to click "edit" on the code page itself and submit as a pull request.     So glad to hear you are enjoying the videos.

**Comment by thetimetraveller** [comment]
You're welcome!

Didn't know about the "edit" feature in Github, I'll do it that way next time. ;)

Miguel Angel
