### ISSUE TITLE
p5.js tutorial - 7.14 drag and drop a file - example file - strange console message

### ISSUE THREAD

**Issue by SetupandDraw** [shiffman/Video-Lesson-Materials#21]
Running the following code, I made form your video tutorial, everything seems to work fine, but  the console gives me a series of strange messages.

// this is the message I get from the console: 18693: Uncaught TypeError: Cannot read property '0' of undefined 

// and here's the code
function setup() {
  var canvas = createCanvas(200, 200);
  background(100);
  
  canvas.drop(gotFile); 
}

function gotFile(file){
  createP(file.name +" "+file.type+" "+file.size);
  var img = createImg(file.data);
  img.hide();
  
  image(img, 0, 0, 200, 200);
}

**Comment by shiffman** [comment]
I added the code example here:

https://github.com/shiffman/Video-Lesson-Materials/tree/master/code_p5.js/7.14_p5.js_drag_and_drop

However, you won't be able to draw the image in `gotFile()`, b/c it might not be ready yet.  You'll need a second callback with `createImg()`.
