### ISSUE TITLE
p5.js Tutorial - 6.4 The Constructor Function in JavaScript

### ISSUE THREAD

**Issue by SetupandDraw** [shiffman/Video-Lesson-Materials#22]
Hi there! 

I was trying to make a timer object in p5JS to practice with the contructor function: everything seems to work fine with the timer but I get a wired error message from the console:

"77: Uncaught SyntaxError: Failed to construct 'AudioContext': number of hardware contexts reached maximum (6)."

I don't really know why I get this, and what does it means... 'AudioContext'? Gulp! I don't even have 77 lines of code?
It would be great to understand what I have done wrong here.
 
Following the code of the two js files I am using for this: 

```javascript
//first one for the timer object 
function Timer(tempTotalTime) {
  this.savedTime; // When timed started
  this.totalTime = tempTotalTime; // How long timer should last

  //starting the timer
  this.start = function() {
    this.savedTime = millis();
  }

  this.checkTime = function() {
    // check how much time has passed  
    var passedTime = millis() - this.savedTime;
    if (passedTime > this.totalTime) {
      return true;
    } else {
      return false;
    }
  }
}

// and another one for the "main program"
var timer;

function setup(){
  timer = new Timer(2000);
  timer.start();
}

function draw(){
  if (timer.checkTime()){
    println("time is finished");
    //timer.start();
  } 
}
```

**Comment by shiffman** [comment]
Just ran your code and it works for me.  Maybe try updating to new p5.js library?  Must be some other unrelated error.
