### ISSUE TITLE
No Device Connected  Cannot Find Devices

### ISSUE THREAD

**Issue by NicoleLu3** [shiffman/Video-Lesson-Materials#23]
Hi Dan,
I have Xbox one and kinect adapter for windows. And I've all ready installed the windows kinect SDK 2.0.But  when I run your demo on processing 3.0 ,it warned me: "No Device Connected"  " Cannot Find Devices"  I have already downloaded the kinectV2 library.

Thanks,
Nicole

**Comment by shiffman** [comment]
Sounds like you have the right setup!  Double check to make sure you've followed all the instructions here:

https://github.com/ThomasLengeling/KinectPV2
