### ISSUE TITLE
10.2 issue

### ISSUE THREAD

**Issue by dotfury** [shiffman/Video-Lesson-Materials#26]
Hi, 

I am getting this error and am not sure what is causing it:

p5.min.js:6 Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)'

I have tried this in Chrome and Firefox, and tried with the github example as well.

**Comment by shiffman** [comment]
Ah, ok, something changed in p5 which broke this example.  I submitted a pull request to fix it:

https://github.com/processing/p5.js/pull/1397

I'm also going to update the "libraries" directory to use temporarily fixed version of p5.dom.
