### ISSUE TITLE
Starfield p5.js version does not produce output as p5

### ISSUE THREAD

**Issue by ashleyjamesbrown** [shiffman/Video-Lesson-Materials#28]
Running under Version 51.0.2704.36 beta (64-bit) Chrome
Mac OSX 10.9.5

Its hard to show a screenshot because they all fly off the screen really fast. Copied and pasted code verbatim and produces this error.

![screen shot 2016-05-11 at 08 39 48](https://cloud.githubusercontent.com/assets/3481580/15173510/57ce73a4-1754-11e6-9c84-b6f252a9ff0d.png)

**Comment by shiffman** [comment]
Check and make sure you have the very latest p5.js library.  Apologies, there's a bug in earlier p5 which causes this example to not work!

**Comment by ashleyjamesbrown** [comment]
fixed. thanks a lot.
