### ISSUE TITLE
A potential problem to be noticed!

### ISSUE THREAD

**Issue by EmbraceLife** [shiffman/Video-Lesson-Materials#4]
If there are two sketch.js files such as sketch.js and sketch2.js, when we run command R we will only see sketch.js work; if we add sketch2.js onto html, we won't see sketch.js work. Does it mean, there will be either one of them is visible at a time? If so, every time we want to see one we need to comment out the other sketch in html file?

**Comment by shiffman** [comment]
Only code from JS files that are referenced in the HTML file will be executed.  I would not try to include two sketches in one "p5.js project."  However, I might use two JS files for one project if I had a lot of code like I do in some of the object examples (in which case both files are referenced in the HTML).

**Comment by EmbraceLife** [comment]
Thanks Dan, so, as for 1.2_p5.js_Color project, I should delete sketch.js and keep sketch2.js instead right?

**Comment by shiffman** [comment]
If I understand you correctly, are you asking what to do if there are more than one example per video?  I would advise creating separate folder / p5.js projects for each, i.e.

```
1.2_color1/sketch.js
1.2_color1/index.html
1.2_color1/libraries
```

```
1.2_color2/sketch.js
1.2_color2/index.html
1.2_color2/libraries
```

Or whatever numbering / naming system makes sense.  See how

**Comment by EmbraceLife** [comment]
I see what you mean, now. So, if there is only one example, just one project folder with only one sketch.js file; if there are more than one example, make more than one project, and giving them different names like you suggested above. Right?

**Comment by shiffman** [comment]
Perfect, yes!

**Comment by EmbraceLife** [comment]
thank you so much for your patience.
