### ISSUE TITLE
how to syn base with my fork?

### ISSUE THREAD

**Issue by EmbraceLife** [shiffman/Video-Lesson-Materials#6]
I have noticed a message on my fork:
> This branch is 2 commits ahead, 1 commit behind shiffman:master. 

Then I went back to git pull and git fetch, my terminal says:
>  Already up-to-date

* Why am I still one commit behind? Did I miss something?

Also, after I pushed another commit a moment ago, and clicked `pull requrest` on my fork, then the page went to your repo, but this time there is no `Create pull request` button to click, even though the page lists two commits needed to be merged: 

* Did I miss something? 
* Or only one commit can be created with pull request at a time?

**Comment by shiffman** [comment]
There's already an open pull request so any more commits you make will automatically get added to this one.  Should I merge it now or wait?

https://github.com/shiffman/Video-Lesson-Materials/pull/5

**Comment by EmbraceLife** [comment]
you can merge them now. It has been updated.

**Comment by EmbraceLife** [comment]
I see the why there is no `create pull request` now. but why on my fork, it says `one commit behind`?

**Comment by shiffman** [comment]
i think this is just because I have additional "merge" commits from pulling your changes that you don't have.  If you add my repo as a remote, i.e.

```
git remote add upstream https://github.com/shiffman/Video-Lesson-Materials.git
```

You can then pull from mine as well to keep up to date

```
git pull upstream master
```

But you can also just ignore b/c it's all set!

**Comment by EmbraceLife** [comment]
I did as you suggested. now the "behind" message is gone.  Thanks!
